iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  # in Hz

  
  # Default Controllers ------------------------------------------------
  TorqueController:
    type: effort_controllers/JointGroupEffortController
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

  PositionTorqueController:
    type: effort_controllers/JointGroupPositionController
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    iiwa_joint_1:
      pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    iiwa_joint_2:
      pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}
    iiwa_joint_3:
      pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    iiwa_joint_4:
      pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    iiwa_joint_5:
      pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}
    iiwa_joint_6:
      pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}
    iiwa_joint_7:
      pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  PositionController:
    type: position_controllers/JointGroupPositionController
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    iiwa_joint_1:  {p: 700,  i: 0.01, d: 100}
    iiwa_joint_2:  {p: 10000,  i: 100, d: 100}
    iiwa_joint_3: {p: 4500,  i: 35, d: 1}
    iiwa_joint_4:  {p: 5500,  i: 60, d: 2}
    iiwa_joint_5: {p: 1000,  i: 30, d: 0.01}
    iiwa_joint_6:  {p: 500,  i: 0.1, d: 0.01}
    iiwa_joint_7: {p: 100,  i: 0.1, d: 0.01}

  PositionTrajectoryController:
    type: position_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

# gazebo_ros_control/pid_gains:
#   iiwa_joint_1:  {p: 700,  i: 0.01, d: 100}
#   iiwa_joint_2:  {p: 10000,  i: 100, d: 100}
#   iiwa_joint_3: {p: 4500,  i: 35, d: 1}
#   iiwa_joint_4:  {p: 5500,  i: 60, d: 2}
#   iiwa_joint_5: {p: 1000,  i: 30, d: 0.01}
#   iiwa_joint_6:  {p: 500,  i: 0.1, d: 0.01}
#   iiwa_joint_7: {p: 100,  i: 0.1, d: 0.01}
